name: base
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - audioread=3.0.0=py37h89c1867_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py37h06a4308_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.0=py37hd667e15_1
  - chardet=4.0.0=py37h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.14.0=py37h89c1867_0
  - conda-build=3.21.9=py37h06a4308_0
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-package-handling=1.8.1=py37h7f8727e_0
  - cryptography=37.0.1=py37h9ce1e76_0
  - cudatoolkit=11.3.1=ha36c431_9
  - cycler=0.11.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_h77c792f_102
  - filelock=3.6.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h7b6447c_0
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipython=7.31.1=py37h06a4308_1
  - jedi=0.18.1=py37h06a4308_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h7f8727e_0
  - kiwisolver=1.4.4=py37h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libarchive=3.5.2=h5de8990_0
  - libffi=3.3=he6710b0_2
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblief=0.11.5=h295c915_1
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=hbc83047_0
  - librosa=0.9.2=pyhd8ed1ab_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-base=3.4.3=py37h1058ff1_2
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.5=py37he7a7128_2
  - numpy-base=1.21.5=py37hf524024_2
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - packaging=23.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patchelf=0.13=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py37h22f2fdc_0
  - pip=22.1.2=py37h06a4308_0
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.8.0=py37h27cfd23_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-lief=0.11.5=py37h295c915_1
  - pycosat=0.6.3=py37h27cfd23_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=py37_1
  - pysoundfile=0.11.0=pyhd8ed1ab_0
  - python=3.7.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=py3.7_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py37h06a4308_0
  - pyyaml=6.0=py37h7f8727e_1
  - readline=8.1.2=h7f8727e_1
  - resampy=0.4.2=pyhd8ed1ab_0
  - ripgrep=12.1.1=0
  - ruamel_yaml=0.15.100=py37h27cfd23_0
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37h6c91a56_2
  - setuptools=61.2.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.2=hc218d9a_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchtext=0.13.1=py37
  - torchvision=0.13.1=py37_cu113
  - tqdm=4.63.0=pyhd3eb1b0_0
  - typing_extensions=4.3.0=py37h06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.12=h7f8727e_1
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - accelerate==0.15.0
    - addict==2.4.0
    - aiofiles==22.1.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - altair==4.2.0
    - ansi2html==1.8.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==22.2.0
    - av==9.2.0
    - babel==2.11.0
    - basicsr==1.4.2
    - bleach==5.0.1
    - cachetools==5.2.1
    - click==8.1.3
    - dash==2.7.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.6.5
    - decorator==4.4.2
    - defusedxml==0.7.1
    - diffusers==0.11.1
    - entrypoints==0.4
    - exceptiongroup==1.1.0
    - facexlib==0.2.5
    - fastapi==0.89.1
    - fastjsonschema==2.16.2
    - ffmpy==0.3.0
    - filterpy==1.4.5
    - fire==0.5.0
    - flask==2.2.2
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - ftfy==6.1.1
    - future==0.18.3
    - gfpgan==1.3.8
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - gradio==3.16.2
    - grpcio==1.51.1
    - h11==0.14.0
    - httpcore==0.16.3
    - httpx==0.23.3
    - huggingface-hub==0.11.1
    - imageio==2.24.0
    - imageio-ffmpeg==0.4.8
    - importlib-metadata==6.0.0
    - importlib-resources==5.10.2
    - iniconfig==2.0.0
    - ipykernel==6.16.2
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.2
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - json5==0.9.11
    - jsonschema==4.17.3
    - jupyter-client==7.4.9
    - jupyter-core==4.12.0
    - jupyter-dash==0.4.2
    - jupyter-server==1.23.5
    - jupyterlab==3.5.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.19.0
    - jupyterlab-widgets==1.1.1
    - linkify-it-py==1.0.3
    - llvmlite==0.39.1
    - lmdb==1.4.0
    - markdown==3.4.1
    - markdown-it-py==2.1.0
    - markupsafe==2.1.2
    - matplotlib==3.5.3
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mistune==2.0.4
    - moviepy==1.0.3
    - multidict==6.0.4
    - nbclassic==0.4.8
    - nbclient==0.7.2
    - nbconvert==7.2.8
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - networkx==2.6.3
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numba==0.56.4
    - oauthlib==3.2.2
    - openai==0.27.2
    - opencv-python==4.7.0.68
    - orjson==3.8.5
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - pkgutil-resolve-name==1.3.10
    - plotly==5.12.0
    - pluggy==1.0.0
    - proglog==0.1.10
    - prometheus-client==0.15.0
    - protobuf==3.20.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodome==3.16.0
    - pydantic==1.10.4
    - pydub==0.25.1
    - pyrsistent==0.19.3
    - pytest==7.2.1
    - python-multipart==0.0.5
    - python-slugify==7.0.0
    - pywavelets==1.3.0
    - pyzmq==25.0.0
    - realesrgan==0.2.5.0
    - regex==2022.10.31
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - retrying==1.3.4
    - rfc3986==1.5.0
    - rsa==4.9
    - scikit-image==0.19.3
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sniffio==1.3.0
    - stable-diffusion-videos==0.8.0
    - starlette==0.22.0
    - tb-nightly==2.12.0a20230113
    - tenacity==8.1.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.2.0
    - terminado==0.17.1
    - text-unidecode==1.3
    - tifffile==2021.11.2
    - tinycss2==1.2.1
    - tokenizers==0.13.2
    - tomli==2.0.1
    - tornado==6.2
    - traitlets==5.8.1
    - transformers==4.25.1
    - uc-micro-py==1.0.1
    - uvicorn==0.20.0
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - websockets==10.4
    - werkzeug==2.2.2
    - widgetsnbextension==3.6.1
    - yapf==0.32.0
    - yarl==1.8.2
    - youtube-dl==2021.12.17
prefix: /opt/conda
